const conversationQuestions = {
    'getting-to-know-each-other': [
        "What was your childhood like?",
        "Where did you grow up, and what do you remember most about it?",
        "What was your favorite thing to do as a child?",
        "What childhood memory still makes you laugh?",
        "What did you dream of becoming when you were young?",
        "What was your favorite childhood tradition?",
        "Were you more adventurous or cautious as a child?",
        "What was your favorite place to visit when you were growing up?",
        "What is something from your childhood you would love to experience again?",
        "What childhood experience shaped who you are today?",
        "How would you describe your family?",
        "Who are you closest to in your family?",
        "What family tradition means the most to you?",
        "What is something your family taught you that you still carry with you?",
        "What role do you usually play in your family?",
        "If you have siblings, what are they like?",
        "What is your favorite memory with your siblings?",
        "Who in your family has influenced you the most?",
        "What makes you feel at home with someone?",
        "What is something you appreciate more about your family as you\u0027ve gotten older?",
        "What kind of student were you at school?",
        "What was your favorite subject?",
        "Did you enjoy school or mostly look forward to leaving?",
        "What were you like as a teenager?",
        "Did you have a large friend group or a few close friends?",
        "What qualities do you look for in a friend?",
        "What makes someone a lifelong friend?",
        "How do you usually spend time with friends?",
        "Are you naturally social, reserved, or somewhere in between?",
        "What\u0027s something people usually discover about you only after knowing you for a while?",
        "What experience has had the biggest impact on who you are?",
        "What period of your life taught you the most?",
        "What is one decision that changed the direction of your life?",
        "What is something you\u0027ve accomplished that you\u0027re proud of?",
        "What is something you understand differently now than you did five years ago?",
        "Who has played an important role in your journey?",
        "What\u0027s one experience you\u0027d never trade, even though it was difficult?",
        "What chapter of your life would you most like to revisit?"
    ],
    'fun-playful': [
        "What\u0027s the funniest thing that\u0027s ever happened to you on a date?",
        "What\u0027s the most embarrassing thing you\u0027ve done in public?",
        "What\u0027s the weirdest compliment you\u0027ve ever received?",
        "What\u0027s the strangest food combination you secretly enjoy?",
        "What\u0027s your most useless talent?",
        "What\u0027s something you\u0027re surprisingly bad at?",
        "What\u0027s the funniest misunderstanding you\u0027ve ever had?",
        "What\u0027s the most ridiculous excuse you\u0027ve ever used?",
        "What\u0027s something you believed as a child that turned out not to be true?",
        "What\u0027s the funniest nickname you\u0027ve ever had?",
        "If we could teleport anywhere for dinner tonight, where would we go?",
        "If you had to live in a movie for a week, which movie would you choose?",
        "If you could instantly master one completely useless skill, what would it be?",
        "If your life were a sitcom, what would it be called?",
        "If we had to start a business together tomorrow, what would we sell?",
        "If you could swap lives with any fictional character for a day, who would you choose?",
        "If you won a huge amount of money tomorrow, what would be your first ridiculous purchase?",
        "If we were contestants on a reality show, what would we probably argue about?",
        "If you could have dinner with your childhood self, what would you tell them?",
        "If you could create one ridiculous holiday, what would it celebrate?",
        "Would You Rather?",
        "Would you rather travel constantly or have your dream home?",
        "Would you rather always be 30 minutes early or 30 minutes late?",
        "Would you rather give up your phone for a month or television for a year?",
        "Would you rather have unlimited free travel or unlimited free food?",
        "Would you rather be able to read minds or see the future?",
        "Would you rather have an adventure every weekend or a completely relaxing weekend every week?",
        "Would you rather sing everything you say or dance everywhere you go?",
        "Would you rather relive your funniest day or your happiest day?",
        "Would you rather plan every date or have your partner surprise you?",
        "Would you rather be stuck on a deserted island with your best friend or your partner?"
    ],
    'interests-hobbies': [
        "What kind of music instantly improves your mood?",
        "What\u0027s a song you never get tired of?",
        "What movie could you watch repeatedly?",
        "What\u0027s the best movie you\u0027ve seen recently?",
        "What\u0027s your comfort show?",
        "What kind of books do you enjoy?",
        "Is there a fictional character you relate to?",
        "What movie or song brings back a strong memory?",
        "What artist or musician would you love to see live?",
        "What\u0027s something popular that you just don\u0027t understand the hype around?",
        "What do you enjoy doing when you have a completely free day?",
        "What\u0027s a hobby you could spend hours doing?",
        "What\u0027s a hobby you\u0027ve always wanted to try?",
        "What activity makes you lose track of time?",
        "Do you prefer active hobbies or relaxing ones?",
        "What\u0027s something you\u0027re currently learning?",
        "What hobby would you love for us to try together?",
        "What activity always puts you in a good mood?",
        "Is there something you enjoyed as a child that you still enjoy today?",
        "What\u0027s a skill you\u0027d love to become really good at?",
        "What\u0027s your favorite type of food?",
        "What\u0027s the best meal you\u0027ve ever had?",
        "Do you enjoy cooking?",
        "What\u0027s your signature dish?",
        "What\u0027s one country you\u0027d love to visit?",
        "What has been your favorite travel experience?",
        "Do you prefer beach holidays, city breaks, or nature escapes?",
        "What\u0027s your ideal weekend getaway?",
        "Would you rather take a luxury holiday or an adventurous one?",
        "What\u0027s an experience you think everyone should have at least once?"
    ],
    'personality-values': [
        "What quality do you admire most in another person?",
        "What does being a good person mean to you?",
        "What personal value is most important to you?",
        "What does honesty mean to you?",
        "What makes someone trustworthy?",
        "What is something you will never compromise on?",
        "What kind of behavior immediately earns your respect?",
        "What makes you lose respect for someone?",
        "How do you show people that you care about them?",
        "What quality do you hope people see in you?",
        "What does a good life mean to you?",
        "What makes you genuinely happy?",
        "What does success mean to you?",
        "What makes life feel meaningful?",
        "What are you most grateful for right now?",
        "Do you value stability or adventure more?",
        "What kind of environment brings out the best in you?",
        "What is something simple that always makes your day better?",
        "What do you think people need more of in their lives?",
        "What would you like to be remembered for?",
        "What kind of person do you want to become?",
        "What\u0027s something you\u0027re currently working on improving?",
        "How do you handle failure?",
        "What\u0027s a lesson you learned the hard way?",
        "What motivates you when things become difficult?",
        "Who inspires you?",
        "What\u0027s something you would like to be braver about?",
        "How do you know when you\u0027ve grown as a person?",
        "What\u0027s a goal you\u0027re currently excited about?",
        "What is one part of yourself you never want to lose?"
    ],
    'romance-attraction': [
        "What was one of the first things you found attractive about me?",
        "What makes someone instantly interesting to you?",
        "What creates chemistry between two people?",
        "What kind of personality do you find attractive?",
        "What makes someone more attractive over time?",
        "What\u0027s your favorite kind of compliment to receive?",
        "Do you believe attraction can grow slowly?",
        "What makes flirting fun for you?",
        "What\u0027s something small that can make you feel butterflies?",
        "What makes someone unforgettable?",
        "What makes a date feel genuinely romantic to you?",
        "What\u0027s your favorite way to receive affection?",
        "What\u0027s your favorite way to show affection?",
        "What small romantic gesture means a lot to you?",
        "What\u0027s your idea of a perfect date?",
        "Do you prefer planned romantic gestures or spontaneous ones?",
        "What\u0027s the most thoughtful romantic gesture you\u0027ve experienced?",
        "What makes you feel especially connected to someone?",
        "What kind of affection makes you feel closest to your partner?",
        "What\u0027s a romantic memory you would love to recreate?",
        "What\u0027s your favorite way to flirt?",
        "What\u0027s something a partner could do that would instantly make you smile?",
        "What\u0027s your idea of a perfect kiss?",
        "What\u0027s the sweetest thing someone could whisper to you?",
        "What kind of date would make you feel like you\u0027re in a romantic movie?",
        "What nickname would you secretly love a partner to give you?",
        "What\u0027s something you find irresistibly charming?",
        "What makes a romantic moment feel natural rather than forced?"
    ],
    'relationships': [
        "What helps you feel heard during a disagreement?",
        "How do you prefer someone to communicate when something is bothering them?",
        "Do you prefer talking about problems immediately or taking time to think?",
        "What does good communication look like to you?",
        "How do you show someone that you\u0027re listening?",
        "What\u0027s something you wish partners understood about the way you communicate?",
        "How do you handle misunderstandings?",
        "What makes it easier for you to open up?",
        "What does trust mean to you in a relationship?",
        "What helps trust grow between two people?",
        "What does loyalty look like to you?",
        "What boundaries are important to you in a relationship?",
        "How do you know when someone respects your boundaries?",
        "Is privacy important in a relationship?",
        "What makes you feel secure with a partner?",
        "What would make it difficult for you to trust someone again?",
        "How important is independence within a relationship?",
        "How do you prefer to resolve conflict?",
        "What makes an argument productive rather than destructive?",
        "What do you need from a partner after a disagreement?",
        "How do you usually apologize?",
        "What makes an apology feel genuine to you?",
        "What\u0027s something every healthy relationship needs?",
        "What does being a good partner mean to you?",
        "How should couples handle major differences?",
        "What should partners always be able to talk about?",
        "What have previous relationships taught you about yourself?"
    ],
    'future-dreams': [
        "What is something you hope to accomplish in the next five years?",
        "What\u0027s a dream you\u0027ve had for a long time?",
        "What motivates your biggest ambitions?",
        "What would you pursue if money wasn\u0027t a concern?",
        "Where would you love to be professionally in ten years?",
        "What\u0027s something you\u0027ve always wanted to build or create?",
        "What personal goal matters most to you right now?",
        "What would make you feel proud of your life?",
        "Where would you love to live for a few years?",
        "What would your dream home look like?",
        "Do you prefer city life, suburban life, or the countryside?",
        "What does your ideal ordinary day look like?",
        "How important is travel in your future?",
        "What kind of lifestyle would make you happiest?",
        "Would you rather have a predictable life or an adventurous one?",
        "What would your perfect weekend look like five years from now?",
        "What does your ideal future relationship look like?",
        "What kind of adventures would you like to experience with a partner?",
        "What does building a life together mean to you?",
        "How important is marriage to you?",
        "What does family mean to you?",
        "Do you imagine having children someday?",
        "What kind of parent would you like to be, if you choose to have children?",
        "How would you like to balance career and relationships?",
        "What traditions would you like to create with a future partner?",
        "What would make a future together feel exciting rather than routine?",
        "What role does financial security play in your idea of a good life?",
        "Are you more of a saver or a spender?",
        "What does financial independence mean to you?",
        "How should couples approach major financial decisions?",
        "What are you willing to spend more money on?",
        "What would you rather have: more money or more free time?",
        "What does a comfortable life look like to you?"
    ],
    'deep-emotional': [
        "What makes you feel emotionally safe with someone?",
        "When do you feel most loved?",
        "What helps you feel understood?",
        "What makes it easier for you to trust someone emotionally?",
        "How do you know when you can truly be yourself around someone?",
        "What does emotional intimacy mean to you?",
        "What makes you feel supported when you\u0027re having a difficult day?",
        "What\u0027s one thing a partner can do to make you feel appreciated?",
        "What\u0027s something you wish people understood about you?",
        "What\u0027s something you\u0027re still learning about yourself?",
        "What is something you\u0027re proud of that you rarely talk about?",
        "What has changed most about you over the past few years?",
        "What is something you once believed about yourself that you\u0027ve since changed?",
        "When do you find it hardest to ask for help?",
        "What helps you feel comfortable being vulnerable?",
        "What part of yourself are you learning to accept?",
        "What\u0027s something you wish you were better at expressing?",
        "What is a dream you haven\u0027t told many people about?",
        "What is something you\u0027re afraid of losing?",
        "What\u0027s a fear you\u0027ve learned to manage?",
        "What experience changed the way you see yourself?",
        "What\u0027s something difficult that made you stronger?",
        "What is a lesson life taught you that you wouldn\u0027t want to forget?",
        "What\u0027s something you hope to heal or grow from?",
        "What would you tell your younger self?",
        "What are you most proud of overcoming?",
        "What kind of support means the most when you\u0027re struggling?",
        "When do you feel most appreciated?",
        "What makes you feel genuinely seen by someone?",
        "What does being loved well look like to you?",
        "What do you need when you\u0027re feeling overwhelmed?",
        "How can a partner make you feel safe enough to be yourself?",
        "What makes you feel emotionally close to someone?",
        "What\u0027s something you wish a partner would notice without you having to ask?",
        "What is one thing you hope your partner always understands about you?",
        "What makes you feel like you truly belong with someone?",
        "What does a deep connection mean to you?"
    ]
};

